### PR TITLE
Add awork as community service

### PR DESCRIPTION
**Pull request by vdurante**
This PR implements awork as a community service. Would appreciate a review and I am also open to any feedbacks!

I have a question:

- I am using awork's entity id (which is a Guid) as projectId, therefore awork Ids will surely not match MOCO's. But, does MOCO do some cross id matching internally, or should I simply return :projectId from the URLs entirely and attempt to use something from the DOM instead?

Thanks!

### CODE REVIEW

**Comment by manubo** [comment]
Thanks for your PR.

The `service.projectId` should contain a MOCO project identifier (project number) if you want a specific project to be pre-selected when tracking time. Usually, the `service.projectId` is read from the DOM. E.g. if the awork project title contains the MOCO project identifier in brackets, "Project title [MOCO-Project-Identifier]", the helper function `projectIdentifierBySelector` can be used to parse identifier.

**Comment by vdurante** [comment]
> Thanks for your PR.
> 
> The `service.projectId` should contain a MOCO project identifier (project number) if you want a specific project to be pre-selected when tracking time. Usually, the `service.projectId` is read from the DOM. E.g. if the awork project title contains the MOCO project identifier in brackets, "Project title [MOCO-Project-Identifier]", the helper function `projectIdentifierBySelector` can be used to parse the project identifier.

@manubo Thanks! Just updated my PR. I believe everything should work now.

**Comment by manubo** [comment]
@vdurante We have release version 2.4.0 of the MOCO browser extension on Firefox with the awork-support. Chrome will follow in the next days. Thanks for your contribution!

**Comment by vdurante** [comment]
@manubo, sorry to bother, but the marketing team is asking if we have a release date for the Chrome extension already. Thanks!

**Comment by manubo** [comment]
@vdurante It's planned for next week.

**Pull request merged**
